Presentation
romans-adi/romans-adi.github.io pull request #7
Opened 2023-04-21 17:47 UTC by romans-adi

_This branch is created especially to fix all the minor issues and present my page in a video._

Sum up of the project: 

- Project styles are built with both plain CSS and CSS framework (Tailwind) classes
- All elements in this project are based on pre-defined color, typography, and layout. Credits are given to the designer in a specific part of manual documentation (README.md)
- Two pages with unique content. Both pages are responsive and have different elements' positioning on the page based on screen width
- Mobile navigation (burger menu) is working properly and not overlaying any element of the page. The width of the menu is based on screen size
- Prospects section elements (cards) are generated dynamically based on data stored in objects' elements in prospects.js file. Data attributes with boolean values are working as togglers for showing and hiding specific cards. Access to the cards is based on cards (object) ids'
- Scrollbar styles added to the project (based on color given in template)
- All data is either generated by free AI or created by project author. All images are not licensed.
- Logo for event and organization is created by author, using free logo maker online

2023-04-21 18:31 UTC, roshan-bajgain requested changes
Hi <STUDENT_MENTION>, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Suggested changes
- [ ] I cannot leave comment there so I am leaving it here. Please implement it.
- [ ] The `Partner` after the `feature speaker` is missing please implement it in you home page. So it look almost identical to the original design.
### Missing parts in desktop version.
![original](https://user-images.githubusercontent.com/81727988/233708066-43141cdf-6487-436b-8250-e8f28705855d.png)
- [ ] You should stick to the design as much as possible. Please make the spacing that looks like original deisgn. In the footer there is spacing on right and left of the page. See image below for reference. Also the home page footer contain white background and about page contain black. Please implement it
### Your design
![his](https://user-images.githubusercontent.com/81727988/233709549-c62a30d5-57ab-42de-9d28-3cde480a3019.png)

### Original design
![original](https://user-images.githubusercontent.com/81727988/233709566-59d87195-d77b-44a5-a914-1c98d8906d46.png)

_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-04-21 18:31 UTC, roshan-bajgain commented on index.html
>          <li class="nav-link p-2"><a href="about#location">Venue</a></li>
- [ ] Everything is good, a small change is required in this header. The pages should look almost identical to the original design so I would suggest please adjust the spacing as there is more space on left and right and there is less space on list. Please see image below for reference
### Your design
![his](https://user-images.githubusercontent.com/81727988/233705856-bab9aadd-1a58-46d8-b34b-c652992534fe.png)


### Original design
![original](https://user-images.githubusercontent.com/81727988/233705927-b18cc862-bd5b-4672-bc50-7474e48bd708.png)

2023-04-21 20:44 UTC, tresorsawasawa requested changes
# STATUS: REQUEST CHANGES :recycle::recycle: 

Hi @romans-adi 
Great work on making the changes requested by the previous reviewer  👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-21 20:44 UTC, tresorsawasawa commented on about.html
>              you a great and wide range of services during this day. Our main goal is to make your day joyful and
- [ ] ASs mentioned by the previous reviewer and for the project requirements, kindly make sure you stick as much as possible to the Behance design. **Make sure you improve your footer design for both About and Home pages**

| Template design | Your Design |
| ---------------- | -------------------- |
| ![Screenshot from 2023-04-21 22-24-57](https://user-images.githubusercontent.com/83042742/233728660-9511e67d-e3e8-4f26-87b0-823e34b59bb6.png) | ![Screenshot from 2023-04-21 22-30-17](https://user-images.githubusercontent.com/83042742/233729407-6b019011-c1c4-4364-8b8b-ae0f0d6fe6a8.png) |

2023-04-21 20:44 UTC, tresorsawasawa commented on about.html
>      </div>
- [ ] Good job trying to make some changes mentioned by the previous reviewer. However, I noticed that there are still some issues design to improve in order to match the template design
### Behance Header design
![Screenshot from 2023-04-21 22-37-43](https://user-images.githubusercontent.com/83042742/233730917-a5402209-ff1e-4c4f-8631-5f606ab0f446.png)

### Home page Header design
![Screenshot from 2023-04-21 22-35-59](https://user-images.githubusercontent.com/83042742/233731035-365c2fbc-b228-4562-80ba-5eae1b3093d6.png)

### About page Header design
![Screenshot from 2023-04-21 22-36-27](https://user-images.githubusercontent.com/83042742/233731090-ec034bc0-18e4-474a-aac3-0c984235dec8.png)

2023-04-22 03:03 UTC, franclobo reviewed
Hi @romans-adi, 

# STATUS: APPROVED 😃 

![leonardo-dicaprio-leo-dicaprio](https://user-images.githubusercontent.com/58642949/233758431-300f2b43-ae6e-400e-bb41-936b9256e86f.gif)

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

## Highlights

- No linter errors ✔️ 
- Descriptive PR ✔️ 
- Correct Github flow ✔️
- Good topic ✔️
- Good UI ✔️
  
Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-04-22 03:20 UTC, romans-adi commented on about.html
>              <p>© 2023 LIL Media Ventures. All rights reserved.</p>
Thank you for the review, @franclobo!

I made this for a picture in the section above (Venue) because following the best practice of UX/UI, content in the section Hall of Fame is not really a good place to implement this. The thing I can do is switch two sections there and add additional pictures to the section Venue.

I absolutely agree with your suggestion related to the Footer section. Just fussed and made an unimportant changes  :)

2023-04-29 02:09 UTC, merged